mappings:
  DataObjectSorterRequirements: Sunnysideup\DataobjectSorter\Api\DataObjectSorterRequirements
  DataObjectSorterDOD: Sunnysideup\DataobjectSorter\DataObjectSorterDOD
  DataObjectSorterController: Sunnysideup\DataobjectSorter\DataObjectSorterController
  DataObjectOneFieldUpdateController: Sunnysideup\DataobjectSorter\DataObjectOneFieldUpdateController
  DataObjectOneRecordUpdateController: Sunnysideup\DataobjectSorter\DataObjectOneRecordUpdateController
  DataObjectSortBaseClass: Sunnysideup\DataobjectSorter\DataObjectSortBaseClass
  DataObjectOneFieldOneRecordUpdateController: Sunnysideup\DataobjectSorter\DataObjectOneFieldOneRecordUpdateController
  DataObjectSorterField: Sunnysideup\DataobjectSorter\Fields\DataObjectSorterField
